import math as math
def line():
    A = float(input("Ingrese el coeficiente A: "))
    B = float(input("Ingrese el coeficiente B: "))
    X1 = float(input("Ingrese el coeficiente X1: "))
    X2 = float(input("Ingrese el coeficiente X2: "))
    print(f"El coeficiente A de su ecuación de la recta es: {A}")
    print(f"El coeficiente B de su ecuación de la recta es: {B}")
    print(f"El coeficiente X1 de su ecuación de la recta es: {X1}")
    print(f"El coeficiente X2 de su ecuación de la recta es: {X2}")
    print("Para la siguiente ecuación:")
    print(f"\t Y = {A}X + {B}")
    P1 = (X1, A*X1 + B)
    P2 = (X2, A*X2 + B)
    print("Dados los siguientes puntos:")
    print("\tP1", P1)
    print("\tP2", P2)
    distancia=math.dist(P1,P2)
    print("\nLa distancia entre ellos es:", distancia)
